### ISSUE TITLE
The Confguration Editors for Ory Hydra & Kratos are broken

### ISSUE THREAD

**Issue by zicklag** [ory/docs#1640]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The Ory Hydra configuration editor doesn't load properly in the docss.

![image](https://github.com/ory/docs/assets/25393315/30436e39-93d1-4bd8-9f73-cf0c0e456f2e)

### Reproducing the bug

Go to this page: https://www.ory.sh/docs/hydra/reference/configuration-editor

I'm using Brave, a Chromium-derived browser.

### Relevant log output

```shell
SyntaxError: Unable to resolve $ref pointer "ory://tracing-config" (at 321.3071bd1a.js:2:24405)
    at Function.r [as syntax] (321.3071bd1a.js:2:24405)
    at l (321.3071bd1a.js:2:7783)
```

### Version

The documentation

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

None

**Comment by vinckr** [comment]
Same for https://www.ory.sh/docs/kratos/reference/configuration-editor

**Comment by vinckr** [comment]
tracked in https://github.com/ory/docs/issues/1901
